# Generated by Django 3.0 on 2024-05-18 14:20

from django.db import migrations
from oc_lettings_site.utils.data_migration_utils import copy_model_data
from django.apps.registry import Apps
from typing import Any


def copy_data(apps: Apps, schema_editor: Any):
    """
    Copies data from one old app to the current app

    Args:
        apps: The app registry.
        schema_editor: The schema editor.

    Returns:
        None
    """

    copy_model_data(
        apps,
        schema_editor,
        "oc_lettings_site",
        "Address",
        "lettings",
        "Address",
    )
    copy_model_data(
        apps,
        schema_editor,
        "oc_lettings_site",
        "Letting",
        "lettings",
        "Letting",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
