# Generated by Django 3.0 on 2024-05-20 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0002_auto_20240518_1420"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="letting",
            options={"verbose_name_plural": "Lettings"},
        ),
    ]
