name: Testing
on: 
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.5

      - name: Set Up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Linting
        run: flake8

      - name: Django Test
        run: python3 manage.py test

      - name: Coverage
        run: |
          coverage run manage.py test
          coverage report --fail-under=80
