name: CI/CD Pipeline
on: 
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.5

      - name: Set Up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Linting
        run: flake8

      - name: Django Test
        run: python3 manage.py test

      - name: Coverage
        run: |
          coverage run manage.py test
          coverage report --fail-under=80
    
  containerize:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.5
    
      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:latest
        
