name: Create container
on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
  workflow_run:
    workflows: ["Testing"]
    types:
        - completed

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4.1.5

        - name: Login to DockerHub
          uses: docker/login-action@v3.1.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v5.3.0
          with:
            context: .
            push: true
            tags: |
                ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ github.sha }}
                ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest
